# https://docs.travis-ci.com/user/reference/osx/
os: "osx"

# Avoid pulling in the Ruby stuff which we have no use for.
language: "minimal"

matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#macos-version
    - osx_image: "xcode9.2"
    - osx_image: "xcode10.1"
    - osx_image: "xcode11"

install:
  - "curl https://nixos.org/nix/install | sh"

script:
  - "nix-build"
  - "nix-shell shell.nix --run 'python ./spike.py'"
