# https://docs.travis-ci.com/user/reference/osx/
os: "osx"

# Avoid pulling in the Ruby stuff which we have no use for.
language: "minimal"

matrix:
  include:
    # https://docs.travis-ci.com/user/reference/osx/#macos-version
    - osx_image: "xcode9.2"
    - osx_image: "xcode10.1"
    - osx_image: "xcode11"

install:
  # Different osx_images have different HomeBrew/Python@2 state.  Joy.
  - "brew install python@2 || brew upgrade python@2 || true"
  - "brew install rustup-init"
  - "rustup-init -y --default-host x86_64-apple-darwin --default-toolchain stable"
  - "source ~/.bash_profile"
  - "python -m virtualenv ~/venv"
  - "source ~/venv/bin/activate"
  - "python -m pip install --upgrade pip"
  - "python -m pip install --editable ."

script:
  - "python ./spike.py"
