# Don't build branch if there is an open PR, to prevent double builds.
# For now, Appveyor will only build PR commits and not commits to master or
# commits on random branches without an associated PR.
skip_branch_with_pr: true

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\bin\\admin\\run_with_env.cmd"

  # Only use pre-installed Python versions, which Appveyor may upgrade to
  # a later point release.
  # See: http://www.appveyor.com/docs/installed-software#python
  matrix:
    - PYTHON_HOME: C:\\PYTHON27-x64
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
    - PYTHON_HOME: C:\\PYTHON37-x64
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

version: "0.999.post{build}"

build_script:
  - "choco install rustup.install --version 1.19.0"
  - "refreshenv"
  - "git submodule init"
  - "git submodule update"
  - "%PYTHON_HOME%\\python setup.py install"
  - "copy spike.py C:\\spike.py"
  - "%PYTHON_HOME%\\Scripts\pip install wheel"
  - "%PYTHON_HOME%\\python setup.py bdist_wheel"
  # # Set up the environment so we can build and test.
  # - "C:\\projects\\privacypass\\.ci\\appveyor\\init.bat"
  # # Use distutils to build the challenge-bypass-ristretto{-ffi} and our extension
  # # module.
  # - "C:\\projects\\privacypass\\.ci\\appveyor\\build.bat"

test_script:
  # Get away from the source directory which will just confuse the Python
  # module system.
  - "cd C:\\"
  # This passes for a test suite.
  - "%PYTHON_HOME%\\python C:\\spike.py"
