name: Build Python Packages

on:
  push

jobs:
  packages:
    name: Build Packages

    strategy:
      matrix:
        os:
          - "ubuntu-18.04"
          - "macos-10.15"

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: actions/checkout@master
    - name: "Finish Checkout"
      run: |
        git submodule update --init --recursive

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Get Packaging Dependencies
      run: |
        pip install wheel

    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
