name: Build Python Packages

on:
  push

jobs:
  macos-packages:
    name: "Build Packages"

    strategy:
      matrix:
        os:
        - "macos-latest"

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: "actions/checkout@master"
    - name: "Finish Checkout"
      run: |
        git submodule update --init --recursive

    - name: "Set up Python 2.7"
      uses: "actions/setup-python@v1"
      with:
        python-version: "2.7"

    - name: "Get Packaging Dependencies"
      run: |
        pip install wheel twine

    - name: "Build Packages"
      run: |
        python setup.py sdist bdist_wheel

    - name: "Upload Packages"
      env:
        TWINE_USERNAME: "__token__"
        # Secret PyPI API key configured in the GitHub web interface.  Visit
        # the project Settings page, find Secrets beneath it.
        TWINE_PASSWORD: "${{ secrets.exarkun_test_pypi_api_key }}"
      run: |
        twine upload --repository testpypi dist/*
