name: Build Python Packages

on:
  push

jobs:
  macos-packages:
    name: "Build macOS Packages"

    strategy:
      matrix:
        os:
        - "macos-latest"
        python-version:
        - "pypy3"

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: "actions/checkout@master"
    - name: "Finish Checkout"
      run: |
        # We need history and tags to compute a version number.  GitHub
        # checkout action doesn't give us either.
        git fetch --tags --unshallow
        git submodule update --init --recursive

    - name: "Get Packaging Dependencies"
      run: |
        pip install wheel twine

    - name: "Build Packages"
      run: |
        python setup.py bdist_wheel

    - name: "Upload Packages"
      env:
        TWINE_USERNAME: "__token__"
        # Secret PyPI API key configured in the GitHub web interface.  Visit
        # the project Settings page, find Secrets beneath it.
        TWINE_PASSWORD: "${{ secrets.exarkun_test_pypi_api_key }}"
      run: |
        twine upload --repository testpypi dist/*

  windows-packages:
    name: "Build Windows Packages"

    strategy:
      matrix:
        os:
        - "windows-latest"
        python-version:
        - "pypy3"

    runs-on: "${{ matrix.os }}"

    steps:
    # Avoid letting Windows newlines confusing milksnake.
    - run: "git config --global core.autocrlf false"
    - uses: "actions/checkout@master"
    - name: "Finish Checkout"
      run: |
        # We need history and tags to compute a version number.  GitHub
        # checkout action doesn't give us either.
        git fetch --tags --unshallow
        git submodule update --init --recursive

    - name: "Get Packaging Dependencies"
      run: |
        pip install wheel twine

    - name: "Build Packages"
      run: |
        python setup.py sdist bdist_wheel

    - name: "Upload Packages"
      env:
        TWINE_USERNAME: "__token__"
        # Secret PyPI API key configured in the GitHub web interface.  Visit
        # the project Settings page, find Secrets beneath it.
        TWINE_PASSWORD: "${{ secrets.exarkun_test_pypi_api_key }}"
      run: |
        twine upload --repository testpypi dist/*

  manylinux2010-packages:
    name: "Build manylinux2010 Packages"

    strategy:
      matrix:
        os:
        - "ubuntu-18.04"
        python-version:
        - "pypy3"

    runs-on: "${{ matrix.os }}"

    steps:
    - uses: "actions/checkout@master"
    - name: "Finish Checkout"
      run: |
        # We need history and tags to compute a version number.  GitHub
        # checkout action doesn't give us either.
        git fetch --tags --unshallow
        git submodule update --init --recursive

    - name: "Inject Rust Installer"
      # Pending resolution to https://github.com/RalfG/python-wheels-manylinux-build/issues/11
      run: |
        mv setup.py setup.py.orig
        echo 'exec open("/github/workspace/.github/workflows/manylinux2010-install-rust.py").read()' > setup.py
        cat setup.py.orig >> setup.py

    - name: "Build a binary wheel and a source tarball"
      uses: "RalfG/python-wheels-manylinux-build@v0.2.2-manylinux2010_x86_64"
      with:
        python-versions: "cp27-cp27m cp27-cp27mu cp37-cp37m"

    - name: "Upload Packages"
      env:
        TWINE_USERNAME: "__token__"
        # Secret PyPI API key configured in the GitHub web interface.  Visit
        # the project Settings page, find Secrets beneath it.
        TWINE_PASSWORD: "${{ secrets.exarkun_test_pypi_api_key }}"
      run: |
        twine upload --repository testpypi dist/*
