name: Build Python Packages

on:
  push

jobs:
  build:
    name: Build Linux Wheel
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: "Finish Checkout"
      run: |
        git submodule update --init --recursive

    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7

    - name: Get Packaging Dependencies
      run: |
        pip install wheel

    - name: Build a binary wheel and a source tarball
      run: |
        python setup.py sdist bdist_wheel
